### ISSUE TITLE
Server: prevent circular hierarchy of tasks

### ISSUE THREAD

**Issue by erikhofer** [xinra-oss/open-gtd#82]
MongoDB can perform recursive queries: https://docs.mongodb.com/manual/reference/operator/aggregation/graphLookup/

**Comment by TBestmann** [comment]
Couldn't we just create a recursive function that finds a certain taskId in the queue of parentIds? If you try to set a parentId, the whole hierarchy is checked upwards until the first task having no parentId.
As far as I see, this should be enough for preventing circular references, since there is no scenario where a parentId can create a circular reference without having the child task in the direct parentId hierarchy of the parent.
